import request from '@/utils/request'

export default {
  list:         (params) => request.get('/admin/users', { params }),
  detail:       (id)     => request.get(`/admin/users/${id}`),
  create:       (data)   => request.post('/admin/users', data),
  update:       (id, data) => request.put(`/admin/users/${id}`, data),
  delete:       (id)     => request.delete(`/admin/users/${id}`),
  toggleStatus: (id)     => request.post(`/admin/users/${id}/toggle-status`),
  recharge:     (id, data) => request.post(`/admin/users/${id}/recharge`, data),
  loginAs:      (id)     => request.post(`/admin/users/${id}/login-as`),
  services:     (id, params) => request.get(`/admin/users/${id}/services`, { params }),
  refreshServiceStatuses: (id, data) => request.post(`/admin/users/${id}/services/refresh-statuses`, data),
  serviceBaseDetail:(id, serviceId) => request.get(`/admin/users/${id}/services/${serviceId}/base`),
  serviceRemoteStatus:(id, serviceId) => request.get(`/admin/users/${id}/services/${serviceId}/remote-status`),
  storeService: (id, data) => request.post(`/admin/users/${id}/services`, data),
  serviceDetail:(id, serviceId, params) => request.get(`/admin/users/${id}/services/${serviceId}`, { params }),
  servicePower: (id, serviceId, data) => request.post(`/admin/users/${id}/services/${serviceId}/power`, data),
  serviceModuleStatus: (id, serviceId, params) => request.get(`/admin/users/${id}/services/${serviceId}/module-status`, { params }),
  serviceReinstallOptions: (id, serviceId, params) => request.get(`/admin/users/${id}/services/${serviceId}/reinstall/options`, { params }),
  serviceResetPassword: (id, serviceId, data) => request.put(`/admin/users/${id}/services/${serviceId}/password/reset`, data),
  serviceReinstall: (id, serviceId, data) => request.put(`/admin/users/${id}/services/${serviceId}/reinstall`, data),
  serviceDelete: (id, serviceId) => request.delete(`/admin/users/${id}/services/${serviceId}`),
  updateServiceMeta: (id, serviceId, data) => request.put(`/admin/users/${id}/services/${serviceId}/meta`, data),
  manualProvisionService: (id, serviceId, data) => request.put(`/admin/users/${id}/services/${serviceId}/manual-provision`, data),
  invoices:     (id, params) => request.get(`/admin/users/${id}/invoices`, { params }),
  invoiceDetail:(id, invoiceId) => request.get(`/admin/users/${id}/invoices/${invoiceId}`),
  refundInvoice:(id, invoiceId, data) => request.post(`/admin/users/${id}/invoices/${invoiceId}/refund`, data),
  refundService:(id, serviceId, data) => request.post(`/admin/users/${id}/services/${serviceId}/refund`, data),
  balanceLogs:  (id, params) => request.get(`/admin/users/${id}/balance-logs`, { params }),
  tickets:      (id, params) => request.get(`/admin/users/${id}/tickets`, { params }),
  operationLogs:(id, params) => request.get(`/admin/users/${id}/operation-logs`, { params }),
  smsLogs:      (id, params) => request.get(`/admin/users/${id}/sms-logs`, { params }),
  emailLogs:    (id, params) => request.get(`/admin/users/${id}/email-logs`, { params }),
  osOptions:    () => request.get('/admin/os-options'),
}
