import { lazyRouteView } from '@caiwu/shared/runtime'
import type { RouteRecordRaw } from 'vue-router'

export const adminRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/login',
    name: 'AdminLogin',
    component: lazyRouteView(() => import('@/views/admin/Login.vue')),
    meta: { title: '管理员登录', guest: true },
  },
  {
    path: '/admin',
    component: lazyRouteView(() => import('@/layout/AdminLayout.vue')),
    redirect: '/admin/dashboard',
    meta: { requireAuth: true, role: 'admin' },
    children: [
      {
        path: 'dashboard',
        name: 'AdminDashboard',
        component: lazyRouteView(() => import('@/views/admin/Dashboard/index.vue')),
        meta: { title: '仪表盘' },
      },
      {
        path: 'users',
        name: 'AdminUsers',
        component: lazyRouteView(() => import('@/views/admin/Users/index.vue')),
        meta: { title: '用户管理' },
      },
      { path: 'users/verification', redirect: '/admin/users?tab=verification' },
      {
        path: 'users/:id',
        name: 'AdminUserDetail',
        component: lazyRouteView(() => import('@/views/admin/Users/detail/index.vue')),
        meta: { title: '用户详情' },
      },
      {
        path: 'tickets',
        name: 'AdminTickets',
        component: lazyRouteView(() => import('@/views/admin/Tickets/index.vue')),
        meta: { title: '工单管理' },
      },
      {
        path: 'ticket-conversations/:id',
        name: 'AdminTicketConversation',
        component: lazyRouteView(() => import('@/views/admin/Tickets/detail.vue')),
        meta: { title: '工单交流' },
      },
      {
        path: 'products',
        name: 'AdminProducts',
        component: lazyRouteView(() => import('@/pages/admin/products/index.vue')),
        meta: { title: '商品管理' },
      },
      {
        path: 'specs',
        name: 'AdminSpecs',
        component: lazyRouteView(() => import('@/views/admin/Products/SpecsPage.vue')),
        meta: { title: '规格管理' },
      },
      {
        path: 'cpu-models',
        name: 'AdminCpuModels',
        component: lazyRouteView(() => import('@/views/admin/Products/CpuModelsPage.vue')),
        meta: { title: 'CPU型号管理' },
      },
      { path: 'products/catalog', redirect: '/admin/products' },
      { path: 'products/traffic-packages', redirect: '/admin/products?tab=traffic-packages' },
      { path: 'products/suppliers', redirect: '/admin/products?tab=suppliers' },
      {
        path: 'orders',
        name: 'AdminOrders',
        component: lazyRouteView(() => import('@/pages/admin/orders/index.vue')),
        meta: { title: '账单管理' },
      },
      { path: 'services', redirect: '/admin/orders?tab=services' },
      {
        path: 'coupons',
        name: 'AdminCoupons',
        component: lazyRouteView(() => import('@/views/admin/Products/CouponsPage.vue')),
        meta: { title: '优惠券' },
      },
      {
        path: 'coupon-campaigns',
        name: 'AdminCouponCampaigns',
        component: lazyRouteView(() => import('@/views/admin/Products/CouponCampaignsPage.vue')),
        meta: { title: '活动券' },
      },
      {
        path: 'referral',
        name: 'AdminReferral',
        component: lazyRouteView(() => import('@/views/admin/Growth/Referral/index.vue')),
        meta: { title: '推广返利' },
      },
      { path: 'growth', redirect: '/admin/member-levels' },
      {
        path: 'member-levels',
        name: 'AdminMemberLevels',
        component: lazyRouteView(() => import('@/views/admin/Growth/MemberLevelsPage.vue')),
        meta: { title: '会员等级' },
      },
      {
        path: 'content',
        name: 'AdminContent',
        component: lazyRouteView(() => import('@/views/admin/ContentCenter/index.vue')),
        meta: { title: '内容中心', contentType: 'notice' },
      },
      { path: 'content/notices', redirect: '/admin/content' },
      { path: 'content/help', redirect: '/admin/content?type=help' },
      {
        path: 'notifications',
        name: 'AdminNotifications',
        component: lazyRouteView(() => import('@/pages/admin/notifications/index.vue')),
        meta: { title: '通知管理' },
      },
      { path: 'notifications/interfaces', redirect: '/admin/notifications' },
      { path: 'notifications/email-templates', redirect: '/admin/notifications?tab=email-templates' },
      {
        path: 'notifications/email-templates/:code',
        name: 'AdminEmailTemplateDetail',
        component: lazyRouteView(() => import('@/views/admin/Notifications/EmailTemplates/index.vue')),
        meta: { title: '模板详情' },
      },
      { path: 'api-directory', redirect: '/admin/notifications?tab=api-directory' },
      { path: 'notifications/sms-logs', redirect: '/admin/logs?tab=sms' },
      { path: 'notifications/email-logs', redirect: '/admin/logs?tab=email' },
      {
        path: 'logs',
        name: 'AdminLogs',
        component: lazyRouteView(() => import('@/pages/admin/logs/index.vue')),
        meta: { title: '日志' },
      },
      { path: 'logs/system', redirect: '/admin/logs?tab=system' },
      { path: 'logs/admin-logins', redirect: '/admin/logs?tab=admin-logins' },
      { path: 'logs/api', redirect: '/admin/logs?tab=api' },
      { path: 'logs/sms', redirect: '/admin/logs?tab=sms' },
      { path: 'logs/email', redirect: '/admin/logs?tab=email' },
      { path: 'logs/tasks', redirect: '/admin/logs?tab=tasks' },
      { path: 'logs/cleanup', redirect: '/admin/logs?tab=cleanup' },
      { path: 'schedules', redirect: '/admin/logs?tab=schedules' },
      {
        path: 'settings',
        name: 'AdminSettings',
        component: lazyRouteView(() => import('@/views/admin/Settings/index.vue')),
        meta: { title: '系统设置', settingPage: 'system' },
      },
      { path: 'settings/basic', redirect: '/admin/settings?tab=system' },
      { path: 'settings/system', redirect: '/admin/settings?tab=system' },
      { path: 'settings/message-limit', redirect: '/admin/settings?tab=system' },
      { path: 'settings/product', redirect: '/admin/settings?tab=product' },
      { path: 'settings/traffic-package', redirect: '/admin/settings?tab=traffic_package' },
      { path: 'settings/payment', redirect: '/admin/settings?tab=payment' },
      { path: 'settings/referral', redirect: '/admin/settings?tab=referral' },
      { path: 'settings/automation', redirect: '/admin/settings?tab=automation' },
      { path: 'settings/site', redirect: '/admin/settings?tab=site_basic' },
      { path: 'settings/site/basic', redirect: '/admin/settings?tab=site_basic' },
      { path: 'settings/site/seo', redirect: '/admin/settings?tab=site_seo' },
      { path: 'settings/site/hero', redirect: '/admin/settings?tab=site_hero' },
      { path: 'site-ops', redirect: '/admin/settings?tab=site_basic' },
    ],
  },
  {
    path: '/',
    redirect: '/admin/login',
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFound',
    component: lazyRouteView(() => import('@/views/common/NotFound.vue')),
    meta: { title: '404' },
  },
]
