<?php

declare(strict_types=1);

const PARTICLE_COUNT = 6200;
const SAMPLE_SIZE = 220;
const ALPHA_THRESHOLD = 110;
const BRIGHTNESS_THRESHOLD = 235;
const SHAPE_SCALE = 5.72;
const SHAPE_DEPTH = 0.12;
const QUANTIZATION_SCALE = 8192;

$shapeFiles = [
    'computer' => '服务器.png',
    'security' => '安全.png',
    'support' => '客服.png',
    'value' => '实惠.png',
    'connection' => '链接.png',
];

$sourceDirectory = realpath(__DIR__ . '/../public/img');
$outputFile = __DIR__ . '/../src/data/heroPointCloudShapes.generated.js';

if ($sourceDirectory === false) {
    fwrite(STDERR, "Unable to resolve image directory.\n");
    exit(1);
}

if (! extension_loaded('gd')) {
    fwrite(STDERR, "The gd extension is required to generate hero point cloud data.\n");
    exit(1);
}

$generatedShapes = [];

foreach ($shapeFiles as $shape => $fileName) {
    $imagePath = $sourceDirectory . DIRECTORY_SEPARATOR . $fileName;

    if (! is_file($imagePath)) {
        fwrite(STDERR, "Missing shape image: {$imagePath}\n");
        exit(1);
    }

    $positions = generateShapePositions($imagePath, $shape);
    $generatedShapes[$shape] = base64_encode(encodeQuantizedPositions($positions));
}

$module = <<<'JS'
// This file is auto-generated by frontend-user-v3-www/scripts/generate_hero_point_cloud_shapes.php
// Do not edit manually.

export const HERO_POINT_CLOUD_PARTICLE_COUNT = %d
export const HERO_POINT_CLOUD_QUANTIZATION_SCALE = %d
export const HERO_POINT_CLOUD_SHAPES = %s
JS;

$moduleContent = sprintf(
    $module,
    PARTICLE_COUNT,
    QUANTIZATION_SCALE,
    json_encode($generatedShapes, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT)
);

if (@file_put_contents($outputFile, $moduleContent . PHP_EOL) === false) {
    fwrite(STDERR, "Failed to write generated module: {$outputFile}\n");
    exit(1);
}

fwrite(STDOUT, "Generated hero point cloud data: {$outputFile}\n");

/**
 * @return array<int, float>
 */
function generateShapePositions(string $imagePath, string $shape): array
{
    mt_srand(abs(crc32($shape)));

    $sourceImage = @imagecreatefrompng($imagePath);
    if ($sourceImage === false) {
        fwrite(STDERR, "Unable to decode PNG image: {$imagePath}\n");
        exit(1);
    }

    $sampleCanvas = imagecreatetruecolor(SAMPLE_SIZE, SAMPLE_SIZE);
    imagealphablending($sampleCanvas, false);
    imagesavealpha($sampleCanvas, true);
    $transparent = imagecolorallocatealpha($sampleCanvas, 0, 0, 0, 127);
    imagefill($sampleCanvas, 0, 0, $transparent);
    imagecopyresampled(
        $sampleCanvas,
        $sourceImage,
        0,
        0,
        0,
        0,
        SAMPLE_SIZE,
        SAMPLE_SIZE,
        imagesx($sourceImage),
        imagesy($sourceImage)
    );
    imagedestroy($sourceImage);

    $solidPixels = [];

    for ($y = 1; $y < SAMPLE_SIZE - 1; $y++) {
        for ($x = 1; $x < SAMPLE_SIZE - 1; $x++) {
            $pixel = readPixel($sampleCanvas, $x, $y);

            if ($pixel['alpha'] <= ALPHA_THRESHOLD || $pixel['brightness'] >= BRIGHTNESS_THRESHOLD) {
                continue;
            }

            $neighborSum = readPixel($sampleCanvas, $x - 1, $y)['alpha']
                + readPixel($sampleCanvas, $x + 1, $y)['alpha']
                + readPixel($sampleCanvas, $x, $y - 1)['alpha']
                + readPixel($sampleCanvas, $x, $y + 1)['alpha'];

            if ($neighborSum < ALPHA_THRESHOLD * 3.2) {
                continue;
            }

            $solidPixels[] = [
                'x' => $x,
                'y' => $y,
                'brightness' => $pixel['brightness'],
            ];
        }
    }

    imagedestroy($sampleCanvas);

    if ($solidPixels === []) {
        return array_fill(0, PARTICLE_COUNT * 3, 0.0);
    }

    $shuffledPixels = $solidPixels;
    for ($index = count($shuffledPixels) - 1; $index > 0; $index--) {
        $randomIndex = mt_rand(0, $index);
        $temporary = $shuffledPixels[$index];
        $shuffledPixels[$index] = $shuffledPixels[$randomIndex];
        $shuffledPixels[$randomIndex] = $temporary;
    }

    $minX = SAMPLE_SIZE;
    $minY = SAMPLE_SIZE;
    $maxX = 0;
    $maxY = 0;

    foreach ($solidPixels as $pixel) {
        $minX = min($minX, $pixel['x']);
        $minY = min($minY, $pixel['y']);
        $maxX = max($maxX, $pixel['x']);
        $maxY = max($maxY, $pixel['y']);
    }

    $centerX = ($minX + $maxX) / 2;
    $centerY = ($minY + $maxY) / 2;
    $largestSide = max($maxX - $minX, $maxY - $minY, 1);
    $positions = [];

    for ($index = 0; $index < PARTICLE_COUNT; $index++) {
        $pixel = $shuffledPixels[$index % count($shuffledPixels)];
        $centeredX = (($pixel['x'] - $centerX) / $largestSide) * SHAPE_SCALE;
        $centeredY = (($centerY - $pixel['y']) / $largestSide) * SHAPE_SCALE;
        $edgeNoise = (255 - $pixel['brightness']) / 255;
        $depth = SHAPE_DEPTH * (0.22 + $edgeNoise * 0.78);

        $positions[] = $centeredX + (randomUnit() - 0.5) * 0.004;
        $positions[] = $centeredY + (randomUnit() - 0.5) * 0.004;
        $positions[] = (randomUnit() - 0.5) * $depth;
    }

    return $positions;
}

/**
 * @return array{alpha: float, brightness: float}
 */
function readPixel(\GdImage $image, int $x, int $y): array
{
    $argb = imagecolorat($image, $x, $y);
    $alpha7Bit = ($argb >> 24) & 0x7F;
    $red = ($argb >> 16) & 0xFF;
    $green = ($argb >> 8) & 0xFF;
    $blue = $argb & 0xFF;

    return [
        'alpha' => (127 - $alpha7Bit) * 255 / 127,
        'brightness' => ($red + $green + $blue) / 3,
    ];
}

function randomUnit(): float
{
    return mt_rand() / mt_getrandmax();
}

function encodeQuantizedPositions(array $positions): string
{
    $quantized = [];

    foreach ($positions as $position) {
        $value = (int) round($position * QUANTIZATION_SCALE);
        $value = max(-32767, min(32767, $value));
        $quantized[] = $value < 0 ? $value + 65536 : $value;
    }

    return pack('v*', ...$quantized);
}
