export const AdminPermissions = {
  ALL: '*',
  DASHBOARD_VIEW: 'dashboard.view',
  USER_LIST: 'user.list',
  USER_DETAIL: 'user.detail',
  USER_MANAGE: 'user.manage',
  USER_RECHARGE: 'user.recharge',
  VERIFICATION_LIST: 'verification.list',
  VERIFICATION_UNBIND: 'verification.unbind',
  ORDER_LIST: 'order.list',
  ORDER_DETAIL: 'order.detail',
  ORDER_MANAGE: 'order.manage',
  INVOICE_LIST: 'invoice.list',
  INVOICE_DETAIL: 'invoice.detail',
  INVOICE_MANAGE: 'invoice.manage',
  TICKET_LIST: 'ticket.list',
  TICKET_REPLY: 'ticket.reply',
  TICKET_MANAGE: 'ticket.manage',
  PRODUCT_LIST: 'product.list',
  PRODUCT_MANAGE: 'product.manage',
  SETTINGS_MANAGE: 'settings.manage',
  LOG_LIST: 'log.list',
  REFERRAL_LIST: 'referral.list',
  FINANCE_REPORT: 'finance.report',
  FINANCE_WITHDRAW: 'finance.withdraw',
  MEMBER_LEVEL_MANAGE: 'member_level.manage',
  CONTENT_LIST: 'content.list',
  CONTENT_MANAGE: 'content.manage',
  STAFF_LIST: 'staff.list',
  STAFF_MANAGE: 'staff.manage',
  ROLE_LIST: 'role.list',
  ROLE_MANAGE: 'role.manage',
  PERMISSION_LIST: 'permission.list',
} as const;

export type AdminPermissionCode = (typeof AdminPermissions)[keyof typeof AdminPermissions];
