import request from '@/utils/request'
import {
  normalizeContentDetailPayload,
  normalizeContentListPayload,
  normalizeContentOverviewPayload,
  withNormalizedData,
} from './contentNormalizer'

const LONG_RUNNING_REQUEST_TIMEOUT = 45000
const LONG_RUNNING_REQUEST_CONFIG = { timeout: LONG_RUNNING_REQUEST_TIMEOUT }

export default {
  services: (params) => request.get('/client/services', { params }),
  groupedOverview: () => request.get('/client/services/grouped-overview'),
  serviceDetail: (id) => request.get(`/client/services/${id}`, { silentError: true }),
  serviceBaseDetail: (id) => request.get(`/client/services/${id}/base`),
  serviceRemoteStatus: (id) => request.get(`/client/services/${id}/remote-status`, { ...LONG_RUNNING_REQUEST_CONFIG, silentError: true }),
  serviceConfig: (id) => request.get(`/client/services/${id}/config`),
  updateServiceName: (id, data) => request.put(`/client/services/${id}/name`, data),
  updateServiceRemark: (id, data) => request.put(`/client/services/${id}/remark`, data),
  serviceTrafficPackages: (id) => request.get(`/client/services/${id}/traffic-packages`),
  quoteTrafficPackage: (id, data) => request.post(`/client/services/${id}/traffic-packages/quote`, data),
  createTrafficPackageOrder: (id, data) => request.post(`/client/services/${id}/traffic-packages/order`, data),
  serviceRenewPreview: (id, params) => request.get(`/client/services/${id}/renew`, { params }),
  createRenewOrder: (id, data) => request.post(`/client/services/${id}/renew`, data),
  updateAutoRenew: (id, data) => request.put(`/client/services/${id}/renew/auto`, data),
  servicePower: (id, data) => request.post(`/client/services/${id}/power`, data),
  serviceModuleStatus: (id, params) => request.get(`/client/services/${id}/module-status`, { params }),
  serviceReinstallOptions: (id, params) => request.get(`/client/services/${id}/reinstall/options`, { params }),
  serviceResetPassword: (id, data) => request.put(`/client/services/${id}/password/reset`, data),
  serviceReinstall: (id, data) => request.put(`/client/services/${id}/reinstall`, data),
  serviceOperationLogs: (id, params) => request.get(`/client/services/${id}/operation-logs`, { params }),
  serviceMonitor: (id, params, config = {}) => request.get(`/client/services/${id}/monitor`, { params, ...config }),
  serviceMonitorBatch: (id, params, config = {}) => request.get(`/client/services/${id}/monitor/batch`, { params, ...config }),
  serviceNatForwardings: (id) => request.get(`/client/services/${id}/nat-forwardings`, LONG_RUNNING_REQUEST_CONFIG),
  createNatForwarding: (id, data) => request.post(`/client/services/${id}/nat-forwardings`, data, LONG_RUNNING_REQUEST_CONFIG),
  deleteNatForwarding: (id, forwardingId) => request.delete(`/client/services/${id}/nat-forwardings/${forwardingId}`, LONG_RUNNING_REQUEST_CONFIG),
  serviceSecurityGroups: (id, params) => request.get(`/client/services/${id}/security-groups`, { params }),
  serviceSecurityGroupRules: (id, groupId) => request.get(`/client/services/${id}/security-groups/${groupId}/rules`),
  createSecurityGroup: (id, data) => request.post(`/client/services/${id}/security-groups`, data),
  applySecurityGroup: (id, groupId) => request.post(`/client/services/${id}/security-groups/${groupId}/apply`),
  deleteSecurityGroup: (id, groupId) => request.delete(`/client/services/${id}/security-groups/${groupId}`),
  createSecurityRule: (id, groupId, data) => request.post(`/client/services/${id}/security-groups/${groupId}/rules`, data),
  deleteSecurityRule: (id, groupId, ruleId) => request.delete(`/client/services/${id}/security-groups/${groupId}/rules/${ruleId}`),
  serviceVnc: (id, config = {}) => request.get(`/client/services/${id}/vnc`, config),
  vncToken: (token) => request.get(`/client/vnc-tokens/${token}`),

  balanceLogs: (params) => request.get('/client/balance-logs', { params }),
  balanceLogsSummary: (params) => request.get('/client/balance-logs/summary', { params }),
  financeLedger: (params) => request.get('/client/finance/ledger', { params }),
  financeLedgerSummary: (params) => request.get('/client/finance/ledger/summary', { params }),
  financeLedgerDetail: (id) => request.get(`/client/finance/ledger/${id}`),
  coupons: (params) => request.get('/client/coupons', { params }),
  couponsSummary: (params) => request.get('/client/coupons/summary', { params }),
  publicCoupons: (params) => request.get('/client/coupons/public', { params }),
  publicCouponsSummary: (params) => request.get('/client/coupons/public/summary', { params }),
  claimCoupon: (couponId) => request.post(`/client/coupons/${couponId}/claim`),

  recharge: (data) => request.post('/client/recharge', data),
  rechargeStatus: (paymentNo, params) => request.get(`/client/recharge/${paymentNo}/status`, { params }),

  invoices: (params) => request.get('/client/invoices', { params }),
  invoicesSummary: (params) => request.get('/client/invoices/summary', { params }),
  createInvoice: (data, config) => request.post('/client/invoices', data, config),
  invoiceDetail: (id) => request.get(`/client/invoices/${id}`),
  cancelInvoice: (id) => request.post(`/client/invoices/${id}/cancel`),
  payInvoiceByBalance: (id, data) => request.post(`/client/invoices/${id}/pay/balance`, data),
  payInvoiceByBalanceAndAlipay: (id, data) => request.post(`/client/invoices/${id}/pay/mix`, data),
  payInvoiceByAlipay: (id, data) => request.post(`/client/invoices/${id}/pay/alipay`, data),
  queryInvoiceAlipayStatus: (id, params) => request.get(`/client/invoices/${id}/pay/alipay/status`, { params }),

  orders: (params) => request.get('/client/orders', { params }),
  ordersSummary: (params) => request.get('/client/orders/summary', { params }),

  payments: (params) => request.get('/client/payments', { params }),
  paymentsSummary: (params) => request.get('/client/payments/summary', { params }),

  referralOverview: () => request.get('/client/referral/overview'),
  referralRewards: (params) => request.get('/client/referral/rewards', { params }),
  referralAccountLogs: (params) => request.get('/client/referral/account-logs', { params }),
  referralWithdrawals: (params) => request.get('/client/referral/withdrawals', { params }),
  applyWithdrawal: (data) => request.post('/client/referral/withdrawals', data),

  tickets: (params) => request.get('/client/tickets', { params }),
  ticketServiceOptions: (params) => request.get('/client/tickets/service-options', { params }),
  ticketDetail: (id) => request.get(`/client/tickets/${id}`),
  createTicket: (data) => request.post('/client/tickets', data),
  replyTicket: (id, data) => request.post(`/client/tickets/${id}/reply`, data),
  recallTicketReply: (id, replyId) => request.post(`/client/tickets/${id}/replies/${replyId}/recall`),
  closeTicket: (id) => request.post(`/client/tickets/${id}/close`),
  uploadTicketImage: (data) => request.post('/client/tickets/upload-image', data, {
    headers: { 'Content-Type': 'multipart/form-data' },
  }),

  contentOverview: () => request.get('/client/content/overview').then((response) => withNormalizedData(response, normalizeContentOverviewPayload)),
  notices: (params) => request.get('/client/notices', { params }).then((response) => withNormalizedData(response, normalizeContentListPayload)),
  noticeDetail: (id) => request.get(`/client/notices/${id}`).then((response) => withNormalizedData(response, normalizeContentDetailPayload)),
  helpArticles: (params) => request.get('/client/help-articles', { params }).then((response) => withNormalizedData(response, normalizeContentListPayload)),
  helpDetail: (id) => request.get(`/client/help-articles/${id}`).then((response) => withNormalizedData(response, normalizeContentDetailPayload)),

  blackholeQuery: (data) => request.post('/client/blackhole/query', data),
  blackholeAddNingboWhitelist: (data) => request.post('/client/blackhole/ningbo/whitelist', data),
  blackholeToggleShiyanLayer7Rule: (data) => request.post('/client/blackhole/shiyan/layer7/toggle', data),
  blackholeAddShiyanLayer4Rule: (data) => request.post('/client/blackhole/shiyan/layer4/add', data),
  blackholeDeleteShiyanLayer4Rule: (data) => request.post('/client/blackhole/shiyan/layer4/delete', data),
}
