import { lazyRouteView } from '@caiwu/shared/runtime'
import type { RouteRecordRaw } from 'vue-router'

export const clientRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    component: lazyRouteView(() => import('@/layout/WebsiteLayout.vue')),
    children: [
      {
        path: '',
        name: 'Home',
        component: lazyRouteView(() => import('@/pages/website/home/index.vue')),
        meta: { title: '首页' },
      },
      {
        path: 'products',
        name: 'Products',
        component: lazyRouteView(() => import('@/pages/website/products/index.vue')),
        meta: { title: '产品与服务' },
      },
      {
        path: 'products/:typeId(\\d+)/:groupId(\\d+)/:childGroupId(\\d+)/:productId(\\d+)',
        name: 'ProductsPurchaseWithChild',
        component: lazyRouteView(() => import('@/pages/website/products/index.vue')),
        meta: { title: '产品与服务' },
      },
      {
        path: 'products/:typeId(\\d+)/:groupId(\\d+)/:productId(\\d+)',
        name: 'ProductsPurchase',
        component: lazyRouteView(() => import('@/pages/website/products/index.vue')),
        meta: { title: '产品与服务' },
      },
      {
        path: 'products/:id',
        name: 'ProductDetail',
        component: lazyRouteView(() => import('@/pages/website/ProductDetail/index.vue')),
        meta: { title: '商品详情' },
      },
      {
        path: 'about',
        name: 'About',
        component: lazyRouteView(() => import('@/pages/website/about/index.vue')),
        meta: { title: '关于我们' },
      },
      {
        path: 'terms',
        name: 'Terms',
        component: lazyRouteView(() => import('@/pages/website/legal-document/index.vue')),
        meta: { title: '服务条款', documentKey: 'terms' },
      },
      {
        path: 'privacy',
        name: 'Privacy',
        component: lazyRouteView(() => import('@/pages/website/legal-document/index.vue')),
        meta: { title: '隐私政策', documentKey: 'privacy' },
      },
      {
        path: 'notices',
        name: 'WebsiteNotices',
        component: lazyRouteView(() => import('@/pages/website/notices/index.vue')),
        meta: { title: '官方公告' },
      },
      {
        path: 'notices/:id',
        name: 'WebsiteNoticeDetail',
        component: lazyRouteView(() => import('@/pages/website/notice-detail/index.vue')),
        meta: { title: '公告详情' },
      },
      {
        path: 'help',
        name: 'WebsiteHelp',
        component: lazyRouteView(() => import('@/pages/website/help/index.vue')),
        meta: { title: '帮助中心' },
      },
      {
        path: 'help/:id',
        name: 'WebsiteHelpDetail',
        component: lazyRouteView(() => import('@/pages/website/help-detail/index.vue')),
        meta: { title: '帮助详情' },
      },
    ],
  },
  {
    path: '/client/login',
    name: 'ClientLogin',
    component: lazyRouteView(() => import('@/pages/client/login/index.vue')),
    meta: { title: '用户登录', guest: true },
  },
  {
    path: '/client/login-as',
    name: 'ClientLoginAs',
    component: lazyRouteView(() => import('@/pages/client/login-as/index.vue')),
    meta: { title: '代登录', guest: true },
  },
  {
    path: '/client/register',
    name: 'ClientRegister',
    component: lazyRouteView(() => import('@/pages/client/register/index.vue')),
    meta: { title: '用户注册', guest: true },
  },
  {
    path: '/client/forgot-password',
    name: 'ClientForgotPassword',
    component: lazyRouteView(() => import('@/pages/client/forgot-password/index.vue')),
    meta: { title: '找回密码', guest: true },
  },
  {
    path: '/client',
    component: lazyRouteView(() => import('@/layout/ClientLayout.vue')),
    redirect: '/client/dashboard',
    meta: { requireAuth: true, role: 'client' },
    children: [
      {
        path: 'dashboard',
        name: 'ClientDashboard',
        component: lazyRouteView(() => import('@/pages/client/dashboard/index.vue')),
        meta: { title: '控制台', icon: 'Odometer' },
      },
      {
        path: 'profile',
        name: 'ClientProfile',
        component: lazyRouteView(() => import('@/pages/client/profile/index.vue')),
        meta: { title: '个人资料' },
      },
      {
        path: 'verification',
        name: 'ClientVerification',
        component: lazyRouteView(() => import('@/pages/client/verification/index.vue')),
        meta: { title: '实名认证', icon: 'User' },
      },
      {
        path: 'order/create',
        name: 'ClientOrderCreate',
        component: lazyRouteView(() => import('@/pages/client/order-create/index.vue')),
        meta: { title: '确认下单' },
      },
      {
        path: 'checkout-resume',
        name: 'ClientCheckoutResume',
        component: lazyRouteView(() => import('@/pages/client/checkout-resume/index.vue')),
        meta: { title: '创建账单中' },
      },
      {
        path: 'services',
        name: 'ClientServices',
        component: lazyRouteView(() => import('@/pages/client/services/index.vue')),
        meta: { title: '我的服务' },
      },
      {
        path: 'services/:id',
        name: 'ClientServiceDetail',
        component: lazyRouteView(() => import('@/pages/client/service-console/index.vue')),
        meta: { title: '实例控制台' },
      },
      { path: 'orders', redirect: '/client/invoices' },
      { path: 'orders/:id', redirect: (to) => `/client/invoices/${to.params.id}` },
      {
        path: 'invoices',
        name: 'ClientInvoices',
        component: lazyRouteView(() => import('@/pages/client/invoices/index.vue')),
        meta: { title: '资金中心' },
      },
      {
        path: 'invoices/:id',
        name: 'ClientInvoiceDetail',
        component: lazyRouteView(() => import('@/pages/client/invoice-detail/index.vue')),
        meta: { title: '账单详情' },
      },
      {
        path: 'catalog',
        name: 'ClientCatalog',
        component: lazyRouteView(() => import('@/pages/client/catalog/index.vue')),
        meta: { title: '产品目录' },
      },
      {
        path: 'recharge',
        name: 'ClientRecharge',
        component: lazyRouteView(() => import('@/pages/client/recharge/index.vue')),
        meta: { title: '账户充值' },
      },
      {
        path: 'balance-logs',
        name: 'ClientBalanceLogs',
        component: lazyRouteView(() => import('@/pages/client/balance-logs/index.vue')),
        meta: { title: '余额流水' },
      },
      {
        path: 'coupons',
        name: 'ClientCoupons',
        component: lazyRouteView(() => import('@/pages/client/coupons/index.vue')),
        meta: { title: '优惠券中心' },
      },
      {
        path: 'referral',
        name: 'ClientReferral',
        component: lazyRouteView(() => import('@/pages/client/referral/index.vue')),
        meta: { title: '推荐奖励' },
      },
      {
        path: 'tickets',
        name: 'ClientTickets',
        component: lazyRouteView(() => import('@/pages/client/tickets/index.vue')),
        meta: { title: '工单支持' },
      },
      {
        path: 'tickets/:id',
        name: 'ClientTicketDetail',
        component: lazyRouteView(() => import('@/pages/client/ticket-detail/index.vue')),
        meta: { title: '工单详情' },
      },
      {
        path: 'ticket-conversations/:id',
        name: 'ClientTicketConversation',
        component: lazyRouteView(() => import('@/pages/client/ticket-detail/index.vue')),
        meta: { title: '工单交流' },
      },
      {
        path: 'tools',
        name: 'ClientToolsShiyan',
        component: lazyRouteView(() => import('@/pages/client/tools/index.vue')),
        meta: { title: '管理工具' },
      },
      {
        path: 'notices',
        name: 'ClientNotices',
        component: lazyRouteView(() => import('@/pages/client/notices/index.vue')),
        meta: { title: '系统公告' },
      },
      {
        path: 'notices/:id',
        name: 'ClientNoticeDetail',
        component: lazyRouteView(() => import('@/pages/client/notice-detail/index.vue')),
        meta: { title: '公告详情' },
      },
      {
        path: 'help',
        name: 'ClientHelp',
        component: lazyRouteView(() => import('@/pages/client/help/index.vue')),
        meta: { title: '帮助中心' },
      },
      {
        path: 'help/:id',
        name: 'ClientHelpDetail',
        component: lazyRouteView(() => import('@/pages/client/help-detail/index.vue')),
        meta: { title: '帮助详情' },
      },
    ],
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFound',
    component: lazyRouteView(() => import('@/pages/common/NotFound.vue')),
    meta: { title: '404' },
  },
]
